### ISSUE TITLE
Issue with Release Version of Estimator Hanging when Piped in Command Line

### ISSUE THREAD

**Issue by boucaron** [Annex-Engineering/klipper_estimator#50]
Hey there,

I've encountered an issue with the release version of the estimator. When I run the following command in the command line with a pipe, the release version gets stuck and doesn't exit:

C:\Users\admin\Downloads>klipper_estimator.exe estimate 3DBenchy_prusaslicer.gcode | findstr inim
Minimal time:                0.824s (0.824s)
Minimal time:                5h44m27.943s (20667.943s)

Interestingly, I don't experience this problem when I run the build with debug symbols.

**Comment by dalegaard** [comment]
Hi @boucaron 

Try running the command with `--omit-layer-times`. I believe the issue is likely caused by the auto-terminal-width system used when printing layer timers. Since you don't need those, you can disable them.

The output of the `estimate` is not meant for machine parsing, so I won't be putting time in to figuring out how to fix this. If you need specific info from the estimate process, you can alsways use the `-f json` option to output JSON instead, and get the specific fields you need from there.

Best regards,
Lasse
